### ISSUE TITLE
it.unimi.dsi.Util.getLogger was removed and unable to call

### ISSUE THREAD

**Issue by titsuki** [U-Alberta/wned#3]
Hi,

I found that `ca.ualberta.entitylinking.graph.DirectedGraph` depends on `es.yrbcn.graph.weighted.WeightedBVGraph` and `WeightedBVGraph` has trouble with initializing a logger:
```
$ java -cp $CP ca.ualberta.entitylinking.graph.DirectedGraph el.config tmp/pageLinkGraph.aggregated 
Exception in thread "main" java.lang.NoSuchMethodError: it.unimi.dsi.Util.getLogger(Ljava/lang/Class;)Lorg/apache/log4j/Logger;
	at es.yrbcn.graph.weighted.WeightedBVGraph.<clinit>(WeightedBVGraph.java:71)
	at ca.ualberta.entitylinking.graph.WeightedGraph.writeGraph(WeightedGraph.java:62)
	at ca.ualberta.entitylinking.graph.DirectedGraph.storeGraph(DirectedGraph.java:92)
	at ca.ualberta.entitylinking.graph.DirectedGraph.main(DirectedGraph.java:243)
```

Cheers,

**Comment by titsuki** [comment]
I also found that `it.unimi.dsi.dsiutils` 2.0.10 has `Util.getLogger` and `DirectedGraph` works.

So, write pom.xml as:
```
            <groupId>it.unimi.dsi</groupId>
            <artifactId>dsiutils</artifactId>
            <version>2.0.10</version>
```
is one of the possible workarounds for this issue.
However, IMHO, it seems better to bundle a `Util.getLogger`-replaced `weightedPR.jar`.
